language: python
python:
#   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
install:
   - pip install SQLAlchemy pycrypto

script:
   - protocol/Protocol.py
   - ./server.py &
   - ./testclient.py
   - sleep 5
   - killall python
