language: python
python:
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
install:
   - pip install SQLAlchemy

script:
   - protocol/Protocol.py
   - ./server.py &
   - sleep 10
   - killall python
